### ISSUE TITLE
Add Bootstrap assets

### ISSUE THREAD

**Issue by achakravarti** [bstarynk/helpcovid#1]
Suggest that we use the Bootstrap framework for the web page front-end -- it's comparatively simple to use to create a responsive design. Suggest that Web front-end assets (such as HTML, CSS, and JS) reside within an `assets` directory.

**Comment by bstarynk** [comment]
On 3/21/20 7:43 AM, Abhishek Chakravarti wrote:
>
> Suggest that we use the Bootstrap framework for the web page front-end 
> -- it's comparatively simple to use to create a responsive design. 
> Suggest that Web front-end assets (such as HTML, CSS, and JS) reside 
> within an |assets| directory.
>

The usual name for that is webroot/

-- 
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France; <basile@starynkevitch.net>
(mobile phone: cf my web page / voir ma page web...)

**Comment by achakravarti** [comment]
Right -- will use that nomenclature.
