### ISSUE TITLE
backup-database.py does not work well

### ISSUE THREAD

**Issue by bstarynk** [bstarynk/helpcovid#19]
In commit a42534f25511e889428ee4 our `backup-database.py` 

- has an option  `--dry-run` which should dump to stdout and be named `--to-stdout` 

- is asking for a PostGreSQL password, but should use what was given at `generate-config.py` or should document in English a way to set the PostGreSQL password

Please document in written English in `DATABASE.md`  how to use that script

**Comment by achakravarti** [comment]
Commit 0c1256fcd79213e12c15dfdef6bad1f5ab53b9d2 resolves this.

**Comment by bstarynk** [comment]
Thanks. Fixed in commit e15d232b25301182f0
