### ISSUE TITLE
bad error web page for missing resource

### ISSUE THREAD

**Issue by bstarynk** [bstarynk/helpcovid#6]
In commit f3212cfe1af088adf7d2 for a non existent resource such as http://localhost:8089/missingfoo the error HTML code is wrong.

Our templates are not correctly expanded. See functions `hcv_expand_template_file` and `hcv_expand_template_input_stream`

The `<?hcv now?>` is not correctly expanded. See file `hcv_template.cc` near line 311 and use `gdb`

**Comment by achakravarti** [comment]
I think this issue is now solved. However, we are still unable to correctly load local webroot assets (CSS, JS, and images)

**Comment by bstarynk** [comment]
closed in git commit f3f19ef3602b499bc4c
